/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HowWeVerifyJobsRouteImport } from './routes/how-we-verify-jobs'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAutomationRouteImport } from './routes/admin.automation'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as PreparationCodingPracticeRouteImport } from './routes/preparation.coding-practice'
import { Route as PreparationInterviewRouteImport } from './routes/preparation.interview'
import { Route as PreparationStudyMaterialRouteImport } from './routes/preparation.study-material'
import { Route as PreparationToolsResourcesRouteImport } from './routes/preparation.tools-resources'
import { Route as JobsLocationRoleCompanyIdRouteImport } from './routes/jobs.$location.$role.$company.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeVerifyJobsRoute = HowWeVerifyJobsRouteImport.update({
  id: '/how-we-verify-jobs',
  path: '/how-we-verify-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutomationRoute = AdminAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PreparationCodingPracticeRoute =
  PreparationCodingPracticeRouteImport.update({
    id: '/preparation/coding-practice',
    path: '/preparation/coding-practice',
    getParentRoute: () => rootRouteImport,
  } as any)
const PreparationInterviewRoute = PreparationInterviewRouteImport.update({
  id: '/preparation/interview',
  path: '/preparation/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const PreparationStudyMaterialRoute =
  PreparationStudyMaterialRouteImport.update({
    id: '/preparation/study-material',
    path: '/preparation/study-material',
    getParentRoute: () => rootRouteImport,
  } as any)
const PreparationToolsResourcesRoute =
  PreparationToolsResourcesRouteImport.update({
    id: '/preparation/tools-resources',
    path: '/preparation/tools-resources',
    getParentRoute: () => rootRouteImport,
  } as any)
const JobsLocationRoleCompanyIdRoute =
  JobsLocationRoleCompanyIdRouteImport.update({
    id: '/jobs/$location/$role/$company/$id',
    path: '/jobs/$location/$role/$company/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/how-we-verify-jobs': typeof HowWeVerifyJobsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/preparation/coding-practice': typeof PreparationCodingPracticeRoute
  '/preparation/interview': typeof PreparationInterviewRoute
  '/preparation/study-material': typeof PreparationStudyMaterialRoute
  '/preparation/tools-resources': typeof PreparationToolsResourcesRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/jobs/$location/$role/$company/$id': typeof JobsLocationRoleCompanyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-we-verify-jobs': typeof HowWeVerifyJobsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/preparation/coding-practice': typeof PreparationCodingPracticeRoute
  '/preparation/interview': typeof PreparationInterviewRoute
  '/preparation/study-material': typeof PreparationStudyMaterialRoute
  '/preparation/tools-resources': typeof PreparationToolsResourcesRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/jobs/$location/$role/$company/$id': typeof JobsLocationRoleCompanyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/how-we-verify-jobs': typeof HowWeVerifyJobsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/preparation/coding-practice': typeof PreparationCodingPracticeRoute
  '/preparation/interview': typeof PreparationInterviewRoute
  '/preparation/study-material': typeof PreparationStudyMaterialRoute
  '/preparation/tools-resources': typeof PreparationToolsResourcesRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/jobs/$location/$role/$company/$id': typeof JobsLocationRoleCompanyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/how-we-verify-jobs'
    | '/privacy'
    | '/profile'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/automation'
    | '/blog/$slug'
    | '/jobs/$id'
    | '/preparation/coding-practice'
    | '/preparation/interview'
    | '/preparation/study-material'
    | '/preparation/tools-resources'
    | '/admin/'
    | '/blog/'
    | '/jobs/'
    | '/jobs/$location/$role/$company/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/how-we-verify-jobs'
    | '/privacy'
    | '/profile'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/automation'
    | '/blog/$slug'
    | '/jobs/$id'
    | '/preparation/coding-practice'
    | '/preparation/interview'
    | '/preparation/study-material'
    | '/preparation/tools-resources'
    | '/admin'
    | '/blog'
    | '/jobs'
    | '/jobs/$location/$role/$company/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/how-we-verify-jobs'
    | '/privacy'
    | '/profile'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/automation'
    | '/blog/$slug'
    | '/jobs/$id'
    | '/preparation/coding-practice'
    | '/preparation/interview'
    | '/preparation/study-material'
    | '/preparation/tools-resources'
    | '/admin/'
    | '/blog/'
    | '/jobs/'
    | '/jobs/$location/$role/$company/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  HowWeVerifyJobsRoute: typeof HowWeVerifyJobsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  JobsIdRoute: typeof JobsIdRoute
  PreparationCodingPracticeRoute: typeof PreparationCodingPracticeRoute
  PreparationInterviewRoute: typeof PreparationInterviewRoute
  PreparationStudyMaterialRoute: typeof PreparationStudyMaterialRoute
  PreparationToolsResourcesRoute: typeof PreparationToolsResourcesRoute
  BlogIndexRoute: typeof BlogIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  JobsLocationRoleCompanyIdRoute: typeof JobsLocationRoleCompanyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-verify-jobs': {
      id: '/how-we-verify-jobs'
      path: '/how-we-verify-jobs'
      fullPath: '/how-we-verify-jobs'
      preLoaderRoute: typeof HowWeVerifyJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/automation': {
      id: '/admin/automation'
      path: '/automation'
      fullPath: '/admin/automation'
      preLoaderRoute: typeof AdminAutomationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparation/coding-practice': {
      id: '/preparation/coding-practice'
      path: '/preparation/coding-practice'
      fullPath: '/preparation/coding-practice'
      preLoaderRoute: typeof PreparationCodingPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparation/interview': {
      id: '/preparation/interview'
      path: '/preparation/interview'
      fullPath: '/preparation/interview'
      preLoaderRoute: typeof PreparationInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparation/study-material': {
      id: '/preparation/study-material'
      path: '/preparation/study-material'
      fullPath: '/preparation/study-material'
      preLoaderRoute: typeof PreparationStudyMaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparation/tools-resources': {
      id: '/preparation/tools-resources'
      path: '/preparation/tools-resources'
      fullPath: '/preparation/tools-resources'
      preLoaderRoute: typeof PreparationToolsResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$location/$role/$company/$id': {
      id: '/jobs/$location/$role/$company/$id'
      path: '/jobs/$location/$role/$company/$id'
      fullPath: '/jobs/$location/$role/$company/$id'
      preLoaderRoute: typeof JobsLocationRoleCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAutomationRoute: typeof AdminAutomationRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAutomationRoute: AdminAutomationRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  HowWeVerifyJobsRoute: HowWeVerifyJobsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  JobsIdRoute: JobsIdRoute,
  PreparationCodingPracticeRoute: PreparationCodingPracticeRoute,
  PreparationInterviewRoute: PreparationInterviewRoute,
  PreparationStudyMaterialRoute: PreparationStudyMaterialRoute,
  PreparationToolsResourcesRoute: PreparationToolsResourcesRoute,
  BlogIndexRoute: BlogIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  JobsLocationRoleCompanyIdRoute: JobsLocationRoleCompanyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
