// Meta's webhook payload shape is only loosely documented and varies by
// event type, so these types are intentionally permissive (lots of optional
// fields) — the parser in utils/webhook-parser.ts is what actually handles
// missing/unexpected fields defensively. Treat these as "best effort" shapes,
// not a guarantee of what Meta will send.

export interface MetaWebhookEnvelope {
  object?: string; // expected "instagram"
  entry?: MetaWebhookEntry[];
}

export interface MetaWebhookEntry {
  id?: string; // Instagram Business Account ID
  time?: number;
  changes?: MetaWebhookChange[]; // comments, mentions
  messaging?: MetaMessagingEvent[]; // messages, deliveries, reads
}

export interface MetaWebhookChange {
  field?: string; // "comments" | "mentions" | ...
  value?: {
    id?: string; // comment id / object id
    text?: string;
    media?: { id?: string; media_product_type?: string };
    from?: { id?: string; username?: string };
    parent_id?: string;
    [key: string]: unknown;
  };
}

export interface MetaMessagingEvent {
  sender?: { id?: string };
  recipient?: { id?: string };
  timestamp?: number;
  message?: {
    mid?: string;
    text?: string;
    is_echo?: boolean;
    quick_reply?: { payload?: string; title?: string };
  };
  postback?: { payload?: string; title?: string; mid?: string };
  is_self?: boolean;
  delivery?: { mids?: string[]; watermark?: number };
  read?: { watermark?: number };
  [key: string]: unknown;
}

// ---------- Normalized internal event ----------

export type InternalEventType =
  | "comment"
  | "mention"
  | "message"
  | "message_interaction"
  | "message_delivery"
  | "message_read"
  | "unknown";

export interface NormalizedWebhookEvent {
  eventType: InternalEventType;
  /** Best available unique-ish identifier for this specific event (comment id, message id, or a synthesized fallback). */
  eventId: string;
  mediaId: string | null;
  userId: string | null;
  /** Only populated when Meta includes it (typically comments) — messaging events don't carry a username. */
  username: string | null;
  commentId: string | null;
  /** Parent comment id when this is a reply to another comment. */
  parentId: string | null;
  messageId: string | null;
  /**
   * Raw comment/message text. Used ONLY transiently by the rule engine for
   * keyword matching; it is never persisted to Firebase (logs store only the
   * short non-sensitive `payloadSummary`), so no personal message content is
   * stored.
   */
  commentText: string | null;
  /** Optional messaging interaction payload (postback / quick reply). */
  interactionPayload: string | null;
  /** Optional messaging interaction title. */
  interactionTitle: string | null;
  /** True when Meta marked the inbound event as an echo of our own message. */
  isEcho: boolean;
  /** True when Meta marked the interaction as generated by the app user itself. */
  isSelf: boolean;
  /** Short, non-sensitive human-readable summary — never the full message/comment text. */
  payloadSummary: string;
}
