export type Level = "Beginner" | "Intermediate" | "Advanced";
export type QA = { q: string; a: string; level: Level };

// Each list has 45 [question, answer] pairs. Levels: first 15 Beginner, next 15 Intermediate, last 15 Advanced.
const build = (rows: [string, string][]): QA[] =>
  rows.map(([q, a], i) => ({ q, a, level: i < 15 ? "Beginner" : i < 30 ? "Intermediate" : "Advanced" }));

const hr: [string, string][] = [
  ["Why do you want to work here?", "Link the company's product, mission or culture to your skills and goals. Be specific; avoid generic praise."],
  ["Why should we hire you?", "Match your top two or three skills to the job needs, with one proof point for each."],
  ["What do you know about our company?", "Mention products, recent news, values and competitors, then connect them to the role."],
  ["Why are you leaving your current job?", "Stay positive: growth, new challenges or learning. Never criticise your employer."],
  ["What motivates you at work?", "Name real drivers such as solving problems, learning or team impact, with a quick example."],
  ["How do you handle pressure?", "Describe prioritising, breaking work into steps and communicating early, with a real example."],
  ["Are you a team player?", "Say yes and give a story where you helped a team deliver, including how you handled disagreement."],
  ["What is your greatest achievement?", "Pick a recent, relevant one. Explain the challenge, your actions and the measurable result."],
  ["How do you manage your time?", "Mention prioritisation, to-do lists, deadlines and tools you use daily."],
  ["What are your hobbies?", "Share genuine interests that show curiosity, discipline or teamwork. Keep it short."],
  ["Are you willing to relocate?", "Answer honestly. If flexible, say so; if not, explain and offer alternatives such as remote work."],
  ["What is your notice period?", "State it clearly and mention whether it is negotiable."],
  ["Do you have any questions for us?", "Ask about team goals, success metrics in the first 90 days and growth paths."],
  ["How would your friends describe you?", "Pick two or three traits relevant to work, each backed by a short example."],
  ["What do you do when you do not know the answer?", "Explain how you research, ask colleagues and verify before delivering."],
  ["Tell me about a time you failed.", "Use STAR, own the mistake, and focus on what you learned and changed afterwards."],
  ["How do you handle criticism?", "Listen without defending, ask clarifying questions, act on it and follow up."],
  ["Describe a time you worked under a tight deadline.", "Show prioritising, trade-offs, communication and the result delivered."],
  ["How do you deal with a difficult coworker?", "Focus on understanding their view, direct communication and a shared goal; escalate only if needed."],
  ["Tell me about a time you showed leadership.", "Leadership can be informal. Show initiative, how you guided others and the outcome."],
  ["How do you prioritise multiple tasks?", "Use urgency and impact, align with your manager and keep stakeholders updated."],
  ["Describe a time you disagreed with your manager.", "Show respect, data-backed reasoning and commitment to the final decision."],
  ["How do you handle ambiguity?", "Clarify goals, make assumptions explicit, start small and adjust with feedback."],
  ["Tell me about a time you learned a new skill quickly.", "Describe your learning plan, resources used and how you applied it."],
  ["What would you do in your first 30 days?", "Learn the team, tools and goals, build relationships and deliver one small win."],
  ["How do you stay updated in your field?", "Mention blogs, courses, communities and side projects, with a recent example."],
  ["How do you handle work-life balance?", "Show boundaries and efficiency while staying committed during critical periods."],
  ["What is your biggest professional regret?", "Choose something minor, show growth and what you do differently now."],
  ["How do you give feedback to a colleague?", "Be specific, timely and kind. Focus on behaviour and impact, and suggest a way forward."],
  ["Tell me about a time you went above and beyond.", "Pick an example with extra effort that clearly benefited the team or customer."],
  ["How would you handle an unrealistic deadline?", "Clarify scope, share a realistic estimate, propose trade-offs and agree on priorities."],
  ["How do you evaluate success in your role?", "Tie it to measurable outcomes, quality, customer impact and team goals."],
  ["Tell me about a time you had to persuade someone.", "Show understanding their concerns, using data and stories, and reaching agreement."],
  ["How do you handle a team member who is not contributing?", "Talk privately first, understand blockers, offer help and set clear expectations."],
  ["Describe a decision you made with incomplete information.", "Explain risks you weighed, how you decided and how you adjusted later."],
  ["How do you handle competing stakeholder demands?", "Align on shared priorities, be transparent on trade-offs and involve a decision-maker."],
  ["Describe your ideal manager.", "Describe clear expectations, feedback and trust, while showing you adapt to different styles."],
  ["How do you build trust in a new team?", "Deliver on small commitments, listen first, be transparent and credit others."],
  ["Tell me about a time you drove change.", "Show the problem, how you got buy-in, the rollout and results."],
  ["How do you handle burnout in yourself or your team?", "Recognise signs early, rebalance workload, communicate and encourage breaks."],
  ["Why is there a gap in your resume?", "Be honest and brief, then highlight skills or learning gained during that time."],
  ["How do you handle a counter-offer?", "Explain that your decision is based on growth and fit, not only money."],
  ["What would make you leave this company?", "Mention lack of growth or learning in general terms, not specific complaints."],
  ["How do you mentor junior colleagues?", "Set goals, give regular feedback, share context and let them own tasks."],
  ["Tell me about a time you handled an ethical dilemma.", "Show your values, who you consulted and a responsible outcome."],
  ["What is your leadership philosophy?", "Describe enabling people, clarity of purpose and accountability, with an example."],
];

const software: [string, string][] = [
  ["What is a variable?", "A named memory location that stores a value which can change during execution."],
  ["What is the difference between compiled and interpreted languages?", "Compiled code is translated to machine code before running; interpreted code is executed line by line at runtime."],
  ["What is a function?", "A reusable block of code that performs a task, can take inputs and can return a value."],
  ["What is recursion?", "A function calling itself on a smaller problem until it reaches a base case."],
  ["What is the difference between stack and queue?", "Stack is LIFO (last in, first out); queue is FIFO (first in, first out)."],
  ["What is an array?", "A fixed-size, ordered collection of elements accessed by index."],
  ["What is a class and an object?", "A class is a blueprint; an object is an instance of that class."],
  ["What is Git and why is it used?", "A distributed version control system to track changes and collaborate on code."],
  ["What is the difference between == and ===?", "== compares after type coercion in JavaScript; === compares value and type without coercion."],
  ["What is an API?", "A defined interface that lets software systems communicate with each other."],
  ["What is a database index?", "A data structure that speeds up lookups at the cost of extra storage and slower writes."],
  ["What is the difference between SQL and NoSQL?", "SQL is relational with fixed schemas and joins; NoSQL covers flexible models such as document, key-value and graph."],
  ["What is a loop?", "A structure that repeats code while a condition holds, such as for and while."],
  ["What is debugging?", "Finding and fixing defects using logs, breakpoints and tests."],
  ["What is the difference between HTTP and HTTPS?", "HTTPS encrypts traffic with TLS; HTTP is plain text."],
  ["What is Big O notation?", "A way to describe how time or space grows with input size, e.g. O(n) or O(log n)."],
  ["Explain how a hash map works.", "It hashes keys to bucket indices for average O(1) lookups, handling collisions with chaining or probing."],
  ["What is the difference between abstract class and interface?", "Abstract classes can hold state and partial implementation; interfaces define contracts only (with limited defaults)."],
  ["What is dependency injection?", "Supplying a class's dependencies from outside instead of creating them inside, improving testability."],
  ["Explain SOLID principles.", "Single responsibility, Open/closed, Liskov substitution, Interface segregation and Dependency inversion."],
  ["What is a deadlock?", "Two or more threads waiting on each other's locks forever. Avoid with lock ordering or timeouts."],
  ["What is the difference between unit and integration testing?", "Unit tests check one component in isolation; integration tests check components working together."],
  ["What is a closure?", "A function that remembers variables from its outer scope even after that scope has finished."],
  ["Explain synchronous vs asynchronous programming.", "Synchronous blocks until a task finishes; asynchronous lets other work continue and handles results later."],
  ["What is ACID in databases?", "Atomicity, Consistency, Isolation and Durability, which guarantee reliable transactions."],
  ["What is normalisation?", "Organising tables to reduce redundancy and improve integrity, using normal forms."],
  ["What is JWT?", "A signed token carrying claims, used for stateless authentication."],
  ["What is CORS?", "A browser mechanism controlling which origins may call a server's resources."],
  ["Explain Git merge vs rebase.", "Merge keeps history with a merge commit; rebase replays commits onto another base for a linear history."],
  ["What is CI/CD?", "Automating build, test and deployment so changes ship quickly and safely."],
  ["Explain the CAP theorem.", "A distributed system can fully provide only two of consistency, availability and partition tolerance."],
  ["What is caching and where would you use it?", "Storing frequently used data in fast storage to cut latency and load, e.g. Redis or a CDN."],
  ["What is the difference between monolith and microservices?", "A monolith is one deployable unit; microservices are independent services with their own deployment and data."],
  ["How does garbage collection work?", "The runtime finds objects no longer reachable and frees their memory automatically."],
  ["What are race conditions and how to prevent them?", "Bugs from unsynchronised concurrent access. Use locks, atomic operations or immutable data."],
  ["Explain database sharding.", "Splitting data across multiple databases by a key to scale horizontally."],
  ["What is a load balancer?", "A component that distributes requests across servers to improve availability and capacity."],
  ["What is idempotency?", "Repeating an operation gives the same result as doing it once, important for safe retries."],
  ["How would you design a rate limiter?", "Use token bucket or sliding window counters per user or IP, stored in a fast store like Redis."],
  ["What is eventual consistency?", "Replicas may differ briefly but converge to the same state if updates stop."],
  ["Explain message queues and when to use them.", "They decouple producers and consumers, smooth traffic spikes and enable async processing (Kafka, RabbitMQ)."],
  ["How do you optimise a slow API endpoint?", "Profile first, then fix queries and indexes, add caching, paginate and reduce payload size."],
  ["What is the difference between optimistic and pessimistic locking?", "Optimistic checks for conflicts at commit; pessimistic locks data up front."],
  ["How do you ensure code quality in a team?", "Code reviews, automated tests, linting, CI checks and clear coding standards."],
  ["Explain how you would design a chat application.", "WebSockets for real-time delivery, a message store, presence service, queues for fan-out and push notifications."],
];

const analyst: [string, string][] = [
  ["What is data analysis?", "Inspecting, cleaning and modelling data to find insights that support decisions."],
  ["What is the difference between data and information?", "Data is raw facts; information is data processed into meaning."],
  ["What is a primary key?", "A column that uniquely identifies each row and cannot be null."],
  ["What is a foreign key?", "A column that references the primary key of another table to link them."],
  ["What is the difference between DELETE, TRUNCATE and DROP?", "DELETE removes rows (can filter), TRUNCATE removes all rows quickly, DROP removes the table itself."],
  ["What is a pivot table?", "A summary tool that groups and aggregates data by chosen rows and columns."],
  ["What does VLOOKUP do?", "Looks up a value in the first column of a range and returns a value from another column."],
  ["What is a KPI?", "A key performance indicator: a measurable value showing progress toward a goal."],
  ["What is an outlier?", "A data point far from the rest that may be an error or a real extreme."],
  ["What is data cleaning?", "Fixing errors, duplicates, missing values and inconsistent formats before analysis."],
  ["What is a histogram?", "A chart showing the distribution of a numeric variable using bins."],
  ["What is the difference between a table and a view?", "A table stores data; a view is a saved query that presents data."],
  ["What is GROUP BY?", "Groups rows with the same values so aggregates like SUM or COUNT apply per group."],
  ["What is a dashboard?", "A visual page of charts and KPIs that monitors performance at a glance."],
  ["What is the difference between structured and unstructured data?", "Structured fits rows and columns; unstructured includes text, images and audio."],
  ["Explain window functions in SQL.", "They compute across related rows without collapsing them, e.g. ROW_NUMBER, RANK, LAG and running SUM."],
  ["What is a CTE?", "A common table expression: a named temporary result defined with WITH to simplify queries."],
  ["What is the difference between RANK and DENSE_RANK?", "RANK leaves gaps after ties; DENSE_RANK does not."],
  ["What is correlation and does it imply causation?", "Correlation measures association; it does not prove one variable causes the other."],
  ["What is standard deviation?", "A measure of how spread out values are around the mean."],
  ["What is a p-value?", "The probability of seeing results at least this extreme if the null hypothesis were true."],
  ["What is A/B testing?", "Comparing two versions with random groups to see which performs better statistically."],
  ["What is a Type I and Type II error?", "Type I is a false positive; Type II is a false negative."],
  ["How do you remove duplicates in SQL?", "Use DISTINCT, GROUP BY, or ROW_NUMBER() to keep one row per key."],
  ["What is the difference between UNION and UNION ALL?", "UNION removes duplicates; UNION ALL keeps them and is faster."],
  ["What is ETL?", "Extract, Transform, Load: moving data from sources, shaping it and loading it into a warehouse."],
  ["What is a data warehouse?", "A central store of cleaned historical data optimised for analysis."],
  ["What is the difference between OLTP and OLAP?", "OLTP handles many small transactions; OLAP handles complex analytical queries."],
  ["What are DAX measures in Power BI?", "Formulas that calculate values dynamically based on filter context."],
  ["What is cohort analysis?", "Grouping users by shared start time or trait and tracking behaviour over time."],
  ["How would you choose the right chart?", "Match the question: trends use lines, comparisons use bars, parts of a whole use stacked bars, relationships use scatter."],
  ["How do you detect outliers?", "Use IQR, z-scores or box plots, then decide to keep, cap or remove them with justification."],
  ["What is the central limit theorem?", "Sample means tend toward a normal distribution as sample size grows."],
  ["What is regression analysis?", "Modelling the relationship between a dependent variable and one or more predictors."],
  ["Explain star schema.", "A central fact table linked to dimension tables, designed for fast analytics."],
  ["How do you validate data quality?", "Check completeness, accuracy, consistency, uniqueness and timeliness with rules and reconciliation."],
  ["What is churn and how do you analyse it?", "Churn is customers leaving. Segment by behaviour, find drivers and compare retained vs lost users."],
  ["How do you calculate retention rate?", "Customers retained at period end divided by customers at period start, excluding new customers."],
  ["What is the difference between inner and anti join?", "Inner keeps matches; anti join keeps rows with no match in the other table."],
  ["How would you present insights to non-technical stakeholders?", "Lead with the answer, use simple visuals, tie to business impact and give clear next steps."],
  ["How do you handle imbalanced data in analysis?", "Use proper metrics (precision, recall), resampling or weighting, and avoid relying on accuracy alone."],
  ["How would you measure the success of a new feature?", "Define a primary metric, guardrail metrics and baseline, then test with an experiment."],
  ["How do you optimise a slow SQL query?", "Check the execution plan, add indexes, filter early, avoid SELECT * and reduce joins."],
  ["How would you build an end-to-end analytics project?", "Define the question, collect and clean data, explore, model or visualise, validate and communicate results."],
  ["What is Simpson's paradox?", "A trend appears in groups but reverses when groups are combined, so always check segments."],
];

const cyber: [string, string][] = [
  ["What is cyber security?", "Protecting systems, networks and data from attacks, damage and unauthorised access."],
  ["What is a firewall?", "A device or software that filters network traffic using security rules."],
  ["What is phishing?", "A social engineering attack that tricks users into revealing credentials or installing malware."],
  ["What is malware?", "Malicious software such as viruses, worms, trojans and ransomware."],
  ["What is a VPN?", "An encrypted tunnel that protects traffic over untrusted networks."],
  ["What is two-factor authentication?", "Login using two proof types, such as a password plus a one-time code."],
  ["What is the difference between a virus and a worm?", "A virus needs a host file to spread; a worm spreads on its own across networks."],
  ["What is ransomware?", "Malware that encrypts files and demands payment for the key."],
  ["What is a strong password policy?", "Long, unique passwords, a password manager, MFA and no reuse."],
  ["What is encryption?", "Converting data into unreadable form so only holders of the key can read it."],
  ["What is hashing?", "A one-way function producing a fixed-size digest, used for integrity and password storage."],
  ["What is a DDoS attack?", "Flooding a service with traffic from many sources to make it unavailable."],
  ["What is social engineering?", "Manipulating people into giving access or information."],
  ["What is a vulnerability, a threat and a risk?", "Vulnerability is a weakness, threat is something that can exploit it, risk is the likelihood and impact."],
  ["What is antivirus and how does it work?", "Software that detects malware using signatures, heuristics and behaviour analysis."],
  ["Explain the OSI model.", "Seven layers: Physical, Data link, Network, Transport, Session, Presentation, Application."],
  ["What is the difference between IDS and IPS?", "IDS detects and alerts; IPS also blocks the traffic."],
  ["What is a man-in-the-middle attack?", "An attacker secretly intercepts or alters communication between two parties. TLS helps prevent it."],
  ["What is CSRF?", "Tricking a logged-in user's browser into sending unwanted requests. Prevent with anti-CSRF tokens and SameSite cookies."],
  ["What is salting a password?", "Adding random data before hashing so identical passwords produce different hashes."],
  ["What is port scanning?", "Probing a host to find open ports and services, often with Nmap."],
  ["What is the difference between TCP and UDP?", "TCP is reliable and connection-oriented; UDP is faster, connectionless and unreliable."],
  ["What is DNS spoofing?", "Corrupting DNS responses to redirect users to malicious sites. DNSSEC helps."],
  ["What is penetration testing?", "Authorised simulated attacks to find and fix security weaknesses."],
  ["What is the principle of least privilege?", "Give users and services only the access they need."],
  ["What is a SIEM?", "A platform that collects and correlates logs to detect and investigate threats."],
  ["What is a zero-day vulnerability?", "A flaw unknown to the vendor with no patch available yet."],
  ["What is multi-factor authentication fatigue?", "Attackers spam approval prompts until a user accepts. Use number matching and alert on repeated prompts."],
  ["Explain TLS handshake basics.", "Client and server agree on versions, ciphers and keys, with the server proving identity via a certificate."],
  ["What is the difference between authentication and authorisation?", "Authentication verifies who you are; authorisation decides what you can do."],
  ["What is threat modelling?", "Identifying assets, attackers and attack paths early, e.g. with STRIDE."],
  ["Explain the OWASP Top 10.", "A list of the most critical web risks such as broken access control, injection and cryptographic failures."],
  ["What is privilege escalation?", "Gaining higher access than intended, either vertical (more rights) or horizontal (another user's)."],
  ["What is SSRF?", "Making a server send requests to internal or unintended targets. Mitigate with allowlists and network segmentation."],
  ["What is a honeypot?", "A decoy system that attracts attackers so their methods can be studied."],
  ["What is lateral movement?", "An attacker moving from one compromised system to others inside a network."],
  ["What is the cyber kill chain?", "Stages of an attack: recon, weaponise, deliver, exploit, install, command and control, actions."],
  ["How do you secure an API?", "Strong authentication, authorisation checks, rate limiting, input validation, TLS and logging."],
  ["What is Zero Trust?", "Never trust by default; verify every user, device and request continuously."],
  ["How do you perform a basic vulnerability assessment?", "Scan assets, prioritise findings by severity and exposure, remediate and rescan."],
  ["What is the difference between a red team and a blue team?", "Red team simulates attackers; blue team defends and detects."],
  ["How would you investigate a suspected phishing email?", "Check headers and links in a sandbox, search for similar mails, block indicators and reset affected accounts."],
  ["What is memory forensics?", "Analysing RAM dumps to find running malware, keys and attacker activity."],
  ["How would you secure a cloud environment?", "Enforce IAM least privilege, encrypt data, enable logging, patch and segment networks, and scan configurations."],
  ["How do you respond to ransomware?", "Isolate affected systems, preserve evidence, identify the strain, restore from clean backups and report as required."],
];

export const EXTRA: Record<string, QA[]> = {
  hr: build(hr),
  software: build(software),
  analyst: build(analyst),
  cyber: build(cyber),
};